import logging
import sys
from fractions import Fraction
from pathlib import Path
from typing import List, Dict

import sage.all
import sage.matrix as mx
from sage.rings.rational_field import QQ
from tioc.get_FORM.form_read_in import Term_Model, Term_s

from autoeft.invariants import SUNTableau, field_projection_operator, symmetrize_tensors
from autoeft.io import load_basis
from autoeft.sun_projection import tensor_projection
from . import AUTOEFT_PATH, model

logger_autoeft = logging.getLogger("autoeft.projection")
logger = logger_autoeft.getChild(__name__)

class TermType(Term_Model):
    """
    Term_s object sorted by their type:
    """
    terms: List[Term_s]
    nD: int  # Number of derivatives in the term.
    field_content: Dict
    mass_dim: int  # mass dimension
    sun_projection_tensors: Dict[str,Dict[str,List[str]]]  # Sun_projection tensors
    sun_projection_matrix: Dict[str, sage.matrix.matrix_rational_dense.Matrix_rational_dense]
    def __init__(self, term : Term_s, nD: int, field_content: Dict):
        self.terms = [term]
        self.n_D = nD
        self.field_content = field_content
        self.mass_dim = term.coeff.dim_operator
        self.sun_projection_tensors = None
        self.sun_projection_matrix = {key: mx.constructor.matrix(QQ, 0, 0, []) for key in model.sun_groups.keys()}

def get_type(terms):
    """
    Summands are sorted by their "type", i.e. field content and derivative.
    Parameters
    ----------
    terms
        Terms generated by converttoSL2C function.
    Returns
    -------
        Sorted terms.
    """
    logger.info("Sort fields by type, indicated by a tuple filled with integers. They specify the "
                "number of fields in the single summand in the following order: "
                f"{' '.join([field.name for field in model.fields.values()])}")
    single_terms = {}  # Ordered terms (by "type") with just a single term in it.
    for term in terms:
        for summand in term.terms:
            typ = summand.fieldcounter.values()
            if summand.coeff == "0":
                continue
            try:
                type(single_terms[tuple(typ)])
                try:
                    assert single_terms[tuple(typ)][summand.n_D].mass_dim == summand.coeff.dim_operator
                    single_terms[tuple(typ)][summand.n_D].terms.append(summand)
                except KeyError:
                    single_terms[tuple(typ)][summand.n_D] = TermType(summand, summand.n_D, summand.fieldcounter_stripped)
            except KeyError:
                single_terms[tuple(typ)] = {summand.n_D: TermType(summand, summand.n_D, summand.fieldcounter_stripped)}

    return single_terms

def sun_internal_projector(op_type, group):
    """Construct a projector to impose the 'internal symmetries'."""
    field_id = 0 #!
    projection_operator = []
    for field, multiplicity in op_type.fields:
        for i in range(multiplicity):
            field_id += 1 #!
            field_tableau = SUNTableau.fill_tableau(
                field_id, field.sun_reprs[group].partition
            )
            projection_operator.append(d:=field_projection_operator(field_tableau))
            # print(field_id, d)
    return projection_operator

def form_basis(op_type, tensors, group):
    """Return monomial and symmetrized tensors in FORM-readable output."""
    internal_projector = sun_internal_projector(op_type, group)

    monomial_basis = []
    tensor_basis = []
    for tensor in tensors:
        monomial_basis.append(tensor.to_form())
        sym_tensors = symmetrize_tensors([(tensor, Fraction(1))], internal_projector)
        tensor_basis.append(SUNTableau.tensors_to_form(sym_tensors))
    return monomial_basis, tensor_basis

def get_basis(max_dim: int):
    """Load basis."""
    basis = {}  # dictionary with basis for each mass dimension from 4 to 6.
    for dim in range(4, max_dim + 1):
        # load_basis also returns some counters and the Hilbert series, which we don't need here...
        try:
            basis[dim], _, _ = load_basis(AUTOEFT_PATH / Path(f"eft/{model.name}/"), dim)
        except FileNotFoundError:
            logger.error(f"No model with the name {model.name} can be found in {AUTOEFT_PATH / Path('eft/')}.")
            sys.exit("STOP")

    return basis

def get_basis_tensors(basis, field_content, derivatives, mass_dim):
    sun_projection_tensors = {}
    for sun_group in model.sun_groups.values():
        # get all the invariants associated with the operator
        op_class, op_subclass, op_type, operator = basis[mass_dim].get_operator(field_content, derivatives)
        # get the SU(N) tensors of sun_group
        sun_basis = operator.sun_tensors[sun_group]
        # convert the tensors to FORM-readable output
        sun_monom, sun_tensor = form_basis(op_type, sun_basis, sun_group)
        sun_projection_tensors[sun_group.name] = {"sun_monom": sun_monom, "sun_tensor": sun_tensor}
        if len(sun_projection_tensors[sun_group.name]["sun_monom"]) == 0:
            sun_projection_tensors[sun_group.name] = False
    return sun_projection_tensors

def sun_projection(single_terms, max_dim: int):
    basis = get_basis(max_dim)
    logger.info(f"Project all terms for a specific type onto the {'-, '.join(list(model.sun_groups.keys()))}-group "
                f"basis when their exist aready one for the specific type.")
    for type in single_terms.values():
        for term_mass_dim in type.values():
            field_content = term_mass_dim.field_content
            derivatives = term_mass_dim.n_D
            mass_dim = term_mass_dim.mass_dim
            try:
                term_mass_dim.sun_projection_tensors = get_basis_tensors(basis, field_content, derivatives, mass_dim)
                # There exists a term in the basis which matches the type and the projection can be done:
                # sun_tensors = list of all su2 tensors contained in all terms of the same type.
                for sun_group, tensors in term_mass_dim.sun_projection_tensors.items():
                    if tensors:
                        N = model.sun_groups[sun_group].N
                        sun_monom  = tensors["sun_monom"]
                        sun_tensor = tensors["sun_tensor"]
                    else:
                        # Since the basis doesn't contain basis tensors for this group, also the tensor itself shouldn't
                        # and thus the next possible SUN group is tried.
                        continue
                    # collect all sun tensors of the group and the tensor in one ordered list for the projection.
                    sun_field_tensors = []
                    for term in term_mass_dim.terms:
                        sun_field_tensors.append(term.gaugeTensorsSUN[sun_group])

                    # project all tensors simultaneously
                    P_map, G_map = tensor_projection(N, sun_monom, sun_tensor, sun_field_tensors)
                    dim = len(sun_monom)
                    n_projection_op = len(sun_field_tensors)
                    G = mx.constructor.matrix(QQ, dim, dim, G_map)
                    P = mx.constructor.matrix(QQ, n_projection_op, dim, P_map)
                    # P*G^(-1) gives the projection matrix
                    projection_matrix = P * G.inverse()
                    term_mass_dim.sun_projection_matrix[sun_group] = projection_matrix
                    logger.debug(f"Projection matrix of {sun_group}-group for field content {term_mass_dim.field_content}:\n{projection_matrix}.")
            except KeyError:
                # Term contains still redundancies and therefore their exist no basis tensor.
                term_mass_dim.sun_projection_tensors = False
    return single_terms