ordinary:
    "[e_C]": "[e_C]"
    "[u_C]": "[u_C]"
    "[d_C]": "[d_C]"
    L: "L"
    Q: "Q"
    "[e_C+]": "[e_C+]"
    "[u_C+]": "[u_C+]"
    "[d_C+]": "[d_C+]"
    "[L+]": "[L+]"
    "[Q+]": "[Q+]"
auxiliary:
    "[e_C]": "[e_Cc]"
    "[u_C]": "[u_Cc]"
    "[d_C]": "[d_Cc]"
    L: "Lc"
    Q: "Qc"
    "[e_C+]": "[e_C+c]"
    "[u_C+]": "[u_C+c]"
    "[d_C+]": "[d_C+c]"
    "[L+]": "[L+c]"
    "[Q+]": "[Q+c]"