(* ::Package:: *)

(*Below is the immediate output generated by my code when integrating out the heavy singlet in the model of https://arxiv.org/abs/2003.05936. 
Included here are only the one-loop contributions to Wilson coefficients up to a factor of 1/(16*pi^2). The result has also been reduced to Warsaw basis and agrees with the result of the paper above. 

Explanation of symbols:
The coupling constants present in the high-scale model are {lambdah,At,g1,g2,g3,mu,lambdaphi,kappa}, where g1,g2,g3 are the gauge couplings. Ms is the mass of the singlet, Mu is the tachyonic mass of the Higgs and eps is the epsilon of DREG. Furthermore L[M1,M2] = Log[M1/M2]. 

There are also couplings that carry indices. In this case these are only the Yukawa couplings {yu,yd,ye,conj[yu],conj[yd],conj[ye]}, but in general there can be more couplings carrying indices. For any coupling C, conj[C] is its complex conjugate.

Besides couplings, there are also fields. Since the EFT is the SMEFT in this case, the only fields present in the output are the SM-fields 
{H,e,u,b,l,q}, which are the Higgs, the right-handed leptons, right-handed up-type quarks, right-handed down-type quarks, the SU(2) lepton doublet and the SU(2) quark doublet. Their conjugates also appear, namely conj[H] and bar[psi] for any fermion psi. Any field is written in the form Name[{ind1},{ind2},{ind3},...,{indN}], where Name is the name of the field, ind1 is the first index carried by the field, ind2 the second, etc. . The order of indices is fixed internally and is currently 
{lor,spin,gauge,gaugeadj,colf,cola,flav} = {4d Lorentz index, spinor index, SU(2)-index in fundamental,SU(2)-index in adjoint,SU(3)-index in fundamental,SU(3)-index in adjoint,flavor index}. Hence, a vector field V carrying an SU(3) index in the adjoint and no other indices would be
V[{lor12},{cola198}]. The numbers attached to the index name are arbitrary in the sense that gauge5289 may appear, but gauge1 may not. This is due to the fact that the code internally handles index contractions and new indices need to be generated during runtime. Of course, in any operator in the final result all of the indices should be properly contracted. 

Apart from the fields, there are also the field strength tensors of U(1),SU(2) and SU(3) named F, V and G in this case. Furthermore, there is the covariant derivative cov[{lor},Field] of any field called Field. This of course carries a Lorentz index.

Beyond couplings and fields, there are also objects like the completely antisymmetric symbol su2eps[{gauge1,gauge2}] and group generators TT[{gaugeadj1},{gauge1, gauge2}].

At this stage everything that carries an index is set to be non-commutative. This is mainly because I internally use some features that wouldn't work if this wasn't the case. Obviously, for fermionic fields it is crucial to avoid accidentally commuting these. Usually I would feed this output to a different code, which translates the operators to Warsaw basis. It isn't a big problem to make everything that is Grassmann even commuting in this output.
*)

{(At*(At*eps - 6*(2 + eps)*mu + 6*eps*mu*L[Ms^2, \[Mu]^2])*
    cov[{lor1}, cov[{lor1}, H[{gauge5289}]]]**
     cov[{lor2}, cov[{lor2}, conj[H][{gauge5289}]]])/(6*eps*Ms^4) + 
  (At*(2*(2 + eps)*Ms^2*mu + At*(eps*Ms^2 + 4*Mu^2 + 5*eps*Mu^2) - 
     2*eps*(Ms^2*mu + At*Mu^2)*L[Ms^2, \[Mu]^2])*cov[{lor1}, H[{gauge4706}]]**
     cov[{lor1}, conj[H][{gauge4706}]])/(2*eps*Ms^4) - 
  (At*mu*(-2 - eps + eps*L[Ms^2, \[Mu]^2])*
    cov[{lor91226}, cov[{lor91226}, H[{gauge91227}]]]**conj[H][{gauge91227}])/
   (2*eps*Ms^2) + (At*mu*(-2 - eps + eps*L[Ms^2, \[Mu]^2])*
    cov[{lor91233}, H[{gauge91234}]]**cov[{lor91235}, 
      cov[{lor91235}, cov[{lor91233}, conj[H][{gauge91234}]]]])/(eps*Ms^4) + 
  (At*mu*(-2 - eps + eps*L[Ms^2, \[Mu]^2])*
    cov[{lor91236}, cov[{lor91237}, cov[{lor91237}, H[{gauge91238}]]]]**
     cov[{lor91236}, conj[H][{gauge91238}]])/(eps*Ms^4) + 
  (2*At*mu*(-2 - eps + eps*L[Ms^2, \[Mu]^2])*
    cov[{lor91239}, cov[{lor91240}, H[{gauge91241}]]]**
     cov[{lor91239}, cov[{lor91240}, conj[H][{gauge91241}]]])/(eps*Ms^4) + 
  (At*mu*(-2 - eps + eps*L[Ms^2, \[Mu]^2])*
    cov[{lor91242}, cov[{lor91242}, cov[{lor91243}, cov[{lor91243}, 
         H[{gauge91244}]]]]]**conj[H][{gauge91244}])/(2*eps*Ms^4) + 
  (At*mu*(-2 - eps + eps*L[Ms^2, \[Mu]^2])*
    cov[{lor91245}, cov[{lor91245}, cov[{lor91246}, H[{gauge91247}]]]]**
     cov[{lor91246}, conj[H][{gauge91247}]])/(eps*Ms^4) + 
  (At*mu*(-2 - eps + eps*L[Ms^2, \[Mu]^2])*
    cov[{lor91251}, cov[{lor91253}, cov[{lor91253}, conj[H][{gauge91252}]]]]**
     cov[{lor91251}, H[{gauge91252}]])/(eps*Ms^4) - 
  (At*mu*(-2 - eps + eps*L[Ms^2, \[Mu]^2])*
    cov[{lor91255}, cov[{lor91255}, conj[H][{gauge91254}]]]**H[{gauge91254}])/
   (2*eps*Ms^2) + (At*mu*(-2 - eps + eps*L[Ms^2, \[Mu]^2])*
    cov[{lor91257}, cov[{lor91257}, cov[{lor91258}, cov[{lor91258}, 
         conj[H][{gauge91256}]]]]]**H[{gauge91256}])/(2*eps*Ms^4) - 
  ((kappa*Ms^6 - At*Ms^4*mu + 2*At^2*(Ms^4 + Ms^2*Mu^2 + Mu^4))*
    (-2 - eps + eps*L[Ms^2, \[Mu]^2])*H[{gauge692}]**conj[H][{gauge692}])/
   (2*eps*Ms^4) - ((I/72)*At^2*g1*(-12 - 17*eps + 6*eps*L[Ms^2, \[Mu]^2])*
    cov[{lor1}, H[{gauge8017}]]**cov[{lor2}, conj[H][{gauge8017}]]**
     F[{lor1, lor2}])/(eps*Ms^4) + 
  ((I/72)*At^2*g1*(-12 - 17*eps + 6*eps*L[Ms^2, \[Mu]^2])*
    cov[{lor1}, conj[H][{gauge8019}]]**cov[{lor2}, H[{gauge8019}]]**
     F[{lor1, lor2}])/(eps*Ms^4) + 
  (At*(-32*(1 + eps)*kappa*Ms^4*mu + 32*At^3*(2 + eps)*(Ms^2 + 2*Mu^2) - 
     32*At^2*mu*(2*Mu^2 + eps*(Ms^2 + 2*Mu^2)) + 
     At*(3*(4 + 3*eps)*g2^2*Ms^4 - 8*(2 + eps)*lambdaphi*Ms^4 + 
       16*(1 + eps)*Ms^2*mu^2 + 64*(2 + eps)*kappa*(Ms^4 + Ms^2*Mu^2 + 
         Mu^4)) - 2*eps*(-8*kappa*Ms^4*mu - 16*At^2*mu*Mu^2 + 
       16*At^3*(Ms^2 + 2*Mu^2) + At*(3*g2^2*Ms^4 - 4*lambdaphi*Ms^4 + 
         4*Ms^2*mu^2 + 32*kappa*(Ms^4 + Ms^2*Mu^2 + Mu^4)))*L[Ms^2, \[Mu]^2])*
    cov[{lor1}, cov[{lor1}, H[{gauge35226}]]]**H[{gauge35053}]**
     conj[H][{gauge35053}]**conj[H][{gauge35226}])/(32*eps*Ms^8) + 
  (At*(-3*At*(4 + 3*eps)*g2^2*Ms^2 - 8*At*(2 + eps)*lambdaphi*Ms^2 - 
     16*(2 + eps)*kappa*Ms^2*mu + 16*At*(1 + eps)*mu^2 + 
     2*eps*(8*kappa*Ms^2*mu + At*(3*g2^2*Ms^2 + 4*lambdaphi*Ms^2 - 4*mu^2))*
      L[Ms^2, \[Mu]^2])*cov[{lor1}, cov[{lor1}, H[{gauge37398}]]]**
     H[{gauge37320}]**conj[H][{gauge37398}]**conj[H][{gauge37320}])/
   (32*eps*Ms^6) + (At*(-32*(1 + eps)*kappa*Ms^4*mu + 
     32*At^3*(2 + eps)*(Ms^2 + 2*Mu^2) - 32*At^2*mu*
      (2*Mu^2 + eps*(Ms^2 + 2*Mu^2)) + At*(3*(4 + 3*eps)*g2^2*Ms^4 - 
       8*(2 + eps)*lambdaphi*Ms^4 + 16*(1 + eps)*Ms^2*mu^2 + 
       64*(2 + eps)*kappa*(Ms^4 + Ms^2*Mu^2 + Mu^4)) - 
     2*eps*(-8*kappa*Ms^4*mu - 16*At^2*mu*Mu^2 + 16*At^3*(Ms^2 + 2*Mu^2) + 
       At*(3*g2^2*Ms^4 - 4*lambdaphi*Ms^4 + 4*Ms^2*mu^2 + 
         32*kappa*(Ms^4 + Ms^2*Mu^2 + Mu^4)))*L[Ms^2, \[Mu]^2])*
    cov[{lor1}, cov[{lor1}, conj[H][{gauge35225}]]]**H[{gauge35053}]**
     H[{gauge35225}]**conj[H][{gauge35053}])/(32*eps*Ms^8) + 
  (At*(-3*At*(4 + 3*eps)*g2^2*Ms^2 - 8*At*(2 + eps)*lambdaphi*Ms^2 - 
     16*(2 + eps)*kappa*Ms^2*mu + 16*At*(1 + eps)*mu^2 + 
     2*eps*(8*kappa*Ms^2*mu + At*(3*g2^2*Ms^2 + 4*lambdaphi*Ms^2 - 4*mu^2))*
      L[Ms^2, \[Mu]^2])*cov[{lor1}, cov[{lor1}, conj[H][{gauge35225}]]]**
     H[{gauge35225}]**H[{gauge35053}]**conj[H][{gauge35053}])/(32*eps*Ms^6) + 
  (At*(-72*(4 + 3*eps)*kappa*Ms^4*mu + 36*At^2*mu*(-3*eps*Ms^2 + eps^2*Ms^2 - 
       8*Mu^2 - 8*eps*Mu^2) - 36*At^3*((-4 + 5*eps + 3*eps^2)*Ms^2 - 
       8*(2 + eps)*Mu^2) + At*(36*Ms^2*((4 + 9*eps)*lambdah*Ms^2 - 
         2*(2 + eps)*lambdaphi*Ms^2 + 4*(1 + eps)*mu^2) - 
       g2^2*Ms^2*((168 + 58*eps + d*(12 + 11*eps))*Ms^2 + 
         72*(2 + eps)*Mu^2) - 36*kappa*((-16 - 5*eps + eps^2)*Ms^4 + 
         2*(-4 + eps)*Ms^2*Mu^2 - 8*(2 + eps)*Mu^4)) + 
     6*eps*(24*kappa*Ms^4*mu - 3*At^2*mu*(eps*Ms^2 - 8*Mu^2) + 
       12*At^3*((-1 + eps)*Ms^2 - 4*Mu^2) + 
       At*(g2^2*((14 + d)*Ms^4 + 12*Ms^2*Mu^2) + 
         3*(-4*Ms^2*(lambdah*Ms^2 - lambdaphi*Ms^2 + mu^2) + 
           kappa*((-16 + eps)*Ms^4 - 8*Ms^2*Mu^2 - 16*Mu^4))))*
      L[Ms^2, \[Mu]^2])*cov[{lor1}, H[{gauge35018}]]**
     cov[{lor1}, conj[H][{gauge35018}]]**H[{gauge34845}]**
     conj[H][{gauge34845}])/(72*eps*Ms^8) + 
  ((-6*At^4*(48 + 112*eps + 33*eps^2) + 12*eps*kappa^2*Ms^4 + 
     96*At^3*eps*mu - 24*At*(24 + 13*eps)*kappa*Ms^2*mu + 
     At^2*(g2^2*((-60 + 24*d - 121*eps + 22*d*eps)*Ms^2 - 
         72*(2 + eps)*Mu^2) + g1^2*((24*(6 + eps) + d*(12 + 11*eps))*Ms^2 + 
         72*(2 + eps)*Mu^2) + 12*(42*eps*lambdah*Ms^2 + 13*eps*mu^2 - 
         20*eps*kappa*(Ms^2 + 3*Mu^2) + 24*(lambdah*Ms^2 + mu^2 - 
           2*kappa*Mu^2))) + 6*At*eps*(6*At^3*(4 + 3*eps) + 
       48*kappa*Ms^2*mu - At*(g2^2*((-5 + 2*d)*Ms^2 - 12*Mu^2) + 
         g1^2*((12 + d)*Ms^2 + 12*Mu^2) + 24*(lambdah*Ms^2 + mu^2 - 
           2*kappa*Mu^2)))*L[Ms^2, \[Mu]^2])*cov[{lor1}, H[{gauge37718}]]**
     cov[{lor1}, H[{gauge37742}]]**conj[H][{gauge37718}]**
     conj[H][{gauge37742}])/(288*eps*Ms^6) + 
  ((-6*At^4*(48 + 112*eps + 33*eps^2) + 12*eps*kappa^2*Ms^4 + 
     96*At^3*eps*mu - 24*At*(24 + 13*eps)*kappa*Ms^2*mu + 
     At^2*(-(g1^2*((168 + 12*d + 58*eps + 11*d*eps)*Ms^2 + 
          72*(2 + eps)*Mu^2)) + g2^2*((168 + 12*d + 58*eps + 11*d*eps)*Ms^2 + 
         72*(2 + eps)*Mu^2) + 12*(54*eps*lambdah*Ms^2 + 13*eps*mu^2 - 
         20*eps*kappa*(Ms^2 + 3*Mu^2) + 24*(lambdah*Ms^2 + mu^2 - 
           2*kappa*Mu^2))) + 6*At*eps*(6*At^3*(4 + 3*eps) + 
       48*kappa*Ms^2*mu + At*(g1^2*((14 + d)*Ms^2 + 12*Mu^2) - 
         g2^2*((14 + d)*Ms^2 + 12*Mu^2) - 24*(lambdah*Ms^2 + mu^2 - 
           2*kappa*Mu^2)))*L[Ms^2, \[Mu]^2])*cov[{lor1}, H[{gauge37718}]]**
     cov[{lor1}, conj[H][{gauge37760}]]**H[{gauge37760}]**
     conj[H][{gauge37718}])/(144*eps*Ms^6) - 
  (At^2*(-2*(12 + 17*eps)*g1^2*Ms^2 - 228*g2^2*Ms^2 + 12*d*g2^2*Ms^2 - 
     179*eps*g2^2*Ms^2 + 11*d*eps*g2^2*Ms^2 - 144*eps*lambdah*Ms^2 - 
     288*g2^2*Mu^2 - 144*eps*g2^2*Mu^2 + 
     6*eps*(2*g1^2*Ms^2 + g2^2*(-((-19 + d)*Ms^2) + 24*Mu^2))*
      L[Ms^2, \[Mu]^2])*cov[{lor1}, H[{gauge4877}]]**
     cov[{lor1}, H[{gauge4742}]]**conj[H][{gauge4742}]**conj[H][{gauge4877}])/
   (288*eps*Ms^6) - ((I/36)*At^2*g2*(-12 - 17*eps + 6*eps*L[Ms^2, \[Mu]^2])*
    cov[{lor1}, H[{gauge8017}]]**cov[{lor2}, conj[H][{gauge7969}]]**
     TT[{gaugeadj8012}, {gauge7969, gauge8017}]**V[{gaugeadj8012}, 
      {lor1, lor2}])/(eps*Ms^4) + 
  ((-6*At^4*(48 + 112*eps + 33*eps^2) + 12*eps*kappa^2*Ms^4 + 
     96*At^3*eps*mu - 24*At*(24 + 13*eps)*kappa*Ms^2*mu + 
     At^2*(g2^2*((-60 + 24*d - 121*eps + 22*d*eps)*Ms^2 - 
         72*(2 + eps)*Mu^2) + g1^2*((24*(6 + eps) + d*(12 + 11*eps))*Ms^2 + 
         72*(2 + eps)*Mu^2) + 12*(42*eps*lambdah*Ms^2 + 13*eps*mu^2 - 
         20*eps*kappa*(Ms^2 + 3*Mu^2) + 24*(lambdah*Ms^2 + mu^2 - 
           2*kappa*Mu^2))) + 6*At*eps*(6*At^3*(4 + 3*eps) + 
       48*kappa*Ms^2*mu - At*(g2^2*((-5 + 2*d)*Ms^2 - 12*Mu^2) + 
         g1^2*((12 + d)*Ms^2 + 12*Mu^2) + 24*(lambdah*Ms^2 + mu^2 - 
           2*kappa*Mu^2)))*L[Ms^2, \[Mu]^2])*
    cov[{lor1}, conj[H][{gauge37720}]]**cov[{lor1}, conj[H][{gauge37760}]]**
     H[{gauge37720}]**H[{gauge37760}])/(288*eps*Ms^6) - 
  (At^2*(-2*(12 + 17*eps)*g1^2*Ms^2 - 228*g2^2*Ms^2 + 12*d*g2^2*Ms^2 - 
     179*eps*g2^2*Ms^2 + 11*d*eps*g2^2*Ms^2 - 144*eps*lambdah*Ms^2 - 
     288*g2^2*Mu^2 - 144*eps*g2^2*Mu^2 + 
     6*eps*(2*g1^2*Ms^2 + g2^2*(-((-19 + d)*Ms^2) + 24*Mu^2))*
      L[Ms^2, \[Mu]^2])*cov[{lor1}, conj[H][{gauge4880}]]**
     cov[{lor1}, conj[H][{gauge4767}]]**H[{gauge4767}]**H[{gauge4880}])/
   (288*eps*Ms^6) + ((I/36)*At^2*g2*(-12 - 17*eps + 6*eps*L[Ms^2, \[Mu]^2])*
    cov[{lor1}, conj[H][{gauge8019}]]**cov[{lor2}, H[{gauge7973}]]**
     TT[{gaugeadj8013}, {gauge8019, gauge7973}]**V[{gaugeadj8013}, 
      {lor1, lor2}])/(eps*Ms^4) + 
  ((2*kappa^2*Ms^6 + 2*At*eps*kappa*Ms^4*mu - 
     4*At^4*((4 + 3*eps)*Ms^2 + 4*(3 + 2*eps)*Mu^2) + 
     4*At^3*mu*(2*Mu^2 + eps*(Ms^2 + 2*Mu^2)) + 
     At^2*(-4*kappa*((4 + 3*eps)*Ms^4 + 2*(3 + 2*eps)*Ms^2*Mu^2 + 
         2*(2 + eps)*Mu^4) + Ms^2*((2 + eps)*lambdaphi*Ms^2 - eps*mu^2 + 
         12*(2 + eps)*lambdah*(Ms^2 + 2*Mu^2))) + 
     eps*(-(kappa^2*Ms^6) - 4*At^3*mu*Mu^2 + 8*At^4*(Ms^2 + 3*Mu^2) + 
       At^2*(-(lambdaphi*Ms^4) - 12*lambdah*Ms^2*(Ms^2 + 2*Mu^2) + 
         4*kappa*(2*Ms^4 + 3*Ms^2*Mu^2 + 2*Mu^4)))*L[Ms^2, \[Mu]^2])*
    H[{gauge1090}]**H[{gauge721}]**conj[H][{gauge1090}]**conj[H][{gauge721}])/
   (4*eps*Ms^6) + (At^2*g1^2*(-12 - 5*eps + 6*eps*L[Ms^2, \[Mu]^2])*
    H[{gauge8055}]**F[{lor1, lor2}]**F[{lor1, lor2}]**conj[H][{gauge8055}])/
   (144*eps*Ms^4) + (At^2*g1*g2*(-12 - 5*eps + 6*eps*L[Ms^2, \[Mu]^2])*
    F[{lor1, lor2}]**H[{gauge8059}]**TT[{gaugeadj8082}, 
      {gauge8144, gauge8059}]**V[{gaugeadj8082}, {lor1, lor2}]**
     conj[H][{gauge8144}])/(36*eps*Ms^4) - 
  ((eps*kappa^3*Ms^8 + 3*At*eps*kappa^2*Ms^6*mu - 
     4*At^6*((54 + 43*eps)*Ms^2 + 9*(2 + eps)*Mu^2) + 
     6*At^5*mu*((14 + 15*eps)*Ms^2 + 2*(10 + 7*eps)*Mu^2) - 
     6*At^4*(-(eps*lambdaphi*Ms^4) + 2*eps*Ms^2*mu^2 - 
       2*lambdaphi*Ms^2*Mu^2 - 2*eps*lambdaphi*Ms^2*Mu^2 + 6*mu^2*Mu^2 + 
       7*eps*mu^2*Mu^2 - 8*lambdah*Ms^2*((6 + 4*eps)*Ms^2 + 
         3*(2 + eps)*Mu^2) + kappa*((42 + 37*eps)*Ms^4 + 
         2*(54 + 37*eps)*Ms^2*Mu^2)) + 
     2*At^3*mu*(6*kappa*((2 + 5*eps)*Ms^4 + 12*(1 + eps)*Ms^2*Mu^2 + 
         (2 + eps)*Mu^4) - Ms^2*((1 + 2*eps)*lambdaphi*Ms^2 - eps*mu^2 + 
         24*lambdah*((1 + eps)*Ms^2 + (4 + 3*eps)*Mu^2))) - 
     6*At^2*Ms^2*(8*(2 + eps)*lambdah^2*Ms^2*(Ms^2 + 3*Mu^2) + 
       kappa^2*((12 + 11*eps)*Ms^4 + (24 + 19*eps)*Ms^2*Mu^2 + 
         6*(2 + eps)*Mu^4) - kappa*Ms^2*((1 + eps)*lambdaphi*Ms^2 - 
         eps*mu^2 + 4*lambdah*((8 + 5*eps)*Ms^2 + 4*(5 + 3*eps)*Mu^2))) + 
     At^2*eps*(36*At^4*(3*Ms^2 + Mu^2) - 6*At^3*mu*(7*Ms^2 + 10*Mu^2) + 
       6*At^2*((-(lambdaphi*Ms^2) + 3*mu^2)*Mu^2 - 24*lambdah*Ms^2*
          (Ms^2 + Mu^2) + 3*kappa*(7*Ms^4 + 18*Ms^2*Mu^2)) + 
       3*Ms^2*(12*kappa^2*(Ms^2 + Mu^2)^2 + 16*lambdah^2*Ms^2*
          (Ms^2 + 3*Mu^2) - kappa*(32*lambdah*Ms^4 + lambdaphi*Ms^4 + 
           80*lambdah*Ms^2*Mu^2)) + At*mu*(lambdaphi*Ms^4 + 
         24*lambdah*(Ms^4 + 4*Ms^2*Mu^2) - 12*kappa*(Ms^4 + 6*Ms^2*Mu^2 + 
           Mu^4)))*L[Ms^2, \[Mu]^2])*H[{gauge1090}]**H[{gauge721}]**
     H[{gauge91150}]**conj[H][{gauge1090}]**conj[H][{gauge721}]**
     conj[H][{gauge91150}])/(12*eps*Ms^10) + 
  (At^2*lambdah*(-2*(At^2*((6 + 4*eps)*Ms^2 + 3*(2 + eps)*Mu^2) - 
       At*mu*((1 + eps)*Ms^2 + (4 + 3*eps)*Mu^2) + 
       Ms^2*((1 + eps)*kappa*Ms^2 + (4 + 3*eps)*kappa*Mu^2 - 
         (2 + eps)*lambdah*(Ms^2 + 3*Mu^2))) + 
     eps*(6*At^2*(Ms^2 + Mu^2) - At*mu*(Ms^2 + 4*Mu^2) + 
       Ms^2*(-2*lambdah*(Ms^2 + 3*Mu^2) + kappa*(Ms^2 + 4*Mu^2)))*
      L[Ms^2, \[Mu]^2])*H[{gauge1188}]**H[{gauge1367}]**H[{gauge1390}]**
     conj[H][{gauge1367}]**conj[H][{gauge1188}]**conj[H][{gauge1390}])/
   (eps*Ms^8) - (2*At^2*lambdah^2*(Ms^2 + 3*Mu^2)*
    (-2 - eps + eps*L[Ms^2, \[Mu]^2])*H[{gauge1413}]**H[{gauge1957}]**
     H[{gauge1708}]**conj[H][{gauge1413}]**conj[H][{gauge1708}]**
     conj[H][{gauge1957}])/(eps*Ms^6) - 
  (At^2*lambdah^2*(Ms^2 + 3*Mu^2)*(-2 - eps + eps*L[Ms^2, \[Mu]^2])*
    H[{gauge1442}]**H[{gauge1687}]**H[{gauge1960}]**conj[H][{gauge1687}]**
     conj[H][{gauge1960}]**conj[H][{gauge1442}])/(2*eps*Ms^6) - 
  (At^2*lambdah^2*(Ms^2 + 3*Mu^2)*(-2 - eps + eps*L[Ms^2, \[Mu]^2])*
    H[{gauge1684}]**H[{gauge1957}]**H[{gauge1413}]**conj[H][{gauge1413}]**
     conj[H][{gauge1684}]**conj[H][{gauge1957}])/(2*eps*Ms^6) + 
  (At^2*g2^2*(-12 - 5*eps + 6*eps*L[Ms^2, \[Mu]^2])*
    H[{gauge8059}]**TT[{gaugeadj8082}, {gauge8109, gauge8059}]**
     TT[{gaugeadj8138}, {gauge8144, gauge8109}]**V[{gaugeadj8082}, 
      {lor1, lor2}]**V[{gaugeadj8138}, {lor1, lor2}]**conj[H][{gauge8144}])/
   (72*eps*Ms^4) + (At^2*g2^2*(-12 - 5*eps + 6*eps*L[Ms^2, \[Mu]^2])*
    H[{gauge8142}]**TT[{gaugeadj8081}, {gauge8055, gauge8105}]**
     TT[{gaugeadj8137}, {gauge8105, gauge8142}]**V[{gaugeadj8081}, 
      {lor1, lor2}]**V[{gaugeadj8137}, {lor1, lor2}]**conj[H][{gauge8055}])/
   (72*eps*Ms^4) - ((I/36)*At^2*g2^3*(-6 - 4*eps + 3*eps*L[Ms^2, \[Mu]^2])*
    H[{gauge86639}]**H[{gauge86858}]**TT[{gaugeadj86853}, 
      {gauge504, gauge86858}]**V[{gaugeadj86853}, {lor1, lor1}]**
     conj[H][{gauge504}]**conj[H][{gauge86639}])/(eps*Ms^4) + 
  ((I/36)*At^2*g2^3*(-6 - 4*eps + 3*eps*L[Ms^2, \[Mu]^2])*
    H[{gauge86831}]**H[{gauge86639}]**TT[{gaugeadj86854}, 
      {gauge86860, gauge86831}]**V[{gaugeadj86854}, {lor1, lor1}]**
     conj[H][{gauge86639}]**conj[H][{gauge86860}])/(eps*Ms^4) - 
  ((I/8)*At^2*(-4 - 5*eps + 2*eps*L[Ms^2, \[Mu]^2])*
    cov[{lor1}, H[{gauge5353}]]**gamma[{lor1}, {spin5953, spin5952}]**
     bar[l][{spin5953}, {gauge5353}, {flav5598}]**l[{spin5952}, {gauge6153}, 
      {flav5951}]**ye[{flav5598, flav5676}]**conj[H][{gauge6153}]**
     conj[ye][{flav5951, flav5676}])/(eps*Ms^4) - 
  ((I/8)*At^2*(-4 - 5*eps + 2*eps*L[Ms^2, \[Mu]^2])*
    cov[{lor1}, H[{gauge5360}]]**gamma[{lor1}, {spin5999, spin5998}]**
     bar[q][{spin5999}, {gauge5360}, {colf5715}, {flav5600}]**
     q[{spin5998}, {gauge6153}, {colf5715}, {flav5997}]**
     yd[{flav5600, flav5716}]**conj[H][{gauge6153}]**
     conj[yd][{flav5997, flav5716}])/(eps*Ms^4) - 
  ((I/8)*At^2*(-4 - 5*eps + 2*eps*L[Ms^2, \[Mu]^2])*
    cov[{lor1}, H[{gauge6153}]]**gamma[{lor1}, {spin5609, spin5610}]**
     e[{spin5610}, {flav5608}]**bar[e][{spin5609}, {flav6113}]**
     ye[{flav5877, flav5608}]**conj[H][{gauge6153}]**
     conj[ye][{flav5877, flav6113}])/(eps*Ms^4) - 
  ((I/8)*At^2*(-4 - 5*eps + 2*eps*L[Ms^2, \[Mu]^2])*
    cov[{lor1}, H[{gauge6153}]]**gamma[{lor1}, {spin5612, spin5613}]**
     b[{spin5613}, {colf5915}, {flav5611}]**bar[b][{spin5612}, {colf5915}, 
      {flav6133}]**yd[{flav5916, flav5611}]**conj[H][{gauge6153}]**
     conj[yd][{flav5916, flav6133}])/(eps*Ms^4) - 
  ((I/8)*At^2*(-4 - 5*eps + 2*eps*L[Ms^2, \[Mu]^2])*
    cov[{lor1}, H[{gauge6153}]]**gamma[{lor1}, {spin6052, spin6051}]**
     bar[u][{spin6052}, {colf5783}, {flav5602}]**u[{spin6051}, {colf5783}, 
      {flav6050}]**yu[{flav5784, flav6050}]**conj[H][{gauge6153}]**
     conj[yu][{flav5784, flav5602}])/(eps*Ms^4) - 
  ((I/8)*At^2*(-4 - 5*eps + 2*eps*L[Ms^2, \[Mu]^2])*
    cov[{lor1}, conj[H][{gauge5329}]]**gamma[{lor1}, {spin5590, spin5591}]**
     H[{gauge6151}]**l[{spin5591}, {gauge5329}, {flav5589}]**
     bar[l][{spin5590}, {gauge6151}, {flav6076}]**ye[{flav6076, flav5826}]**
     conj[ye][{flav5589, flav5826}])/(eps*Ms^4) - 
  ((I/8)*At^2*(-4 - 5*eps + 2*eps*L[Ms^2, \[Mu]^2])*
    cov[{lor1}, conj[H][{gauge5336}]]**gamma[{lor1}, {spin5593, spin5594}]**
     H[{gauge6151}]**q[{spin5594}, {gauge5336}, {colf5868}, {flav5592}]**
     bar[q][{spin5593}, {gauge6151}, {colf5868}, {flav6108}]**
     yd[{flav6108, flav5869}]**conj[yd][{flav5592, flav5869}])/(eps*Ms^4) - 
  ((I/8)*At^2*(-4 - 5*eps + 2*eps*L[Ms^2, \[Mu]^2])*
    cov[{lor1}, conj[H][{gauge6151}]]**gamma[{lor1}, {spin5596, spin5597}]**
     H[{gauge6151}]**u[{spin5597}, {colf5905}, {flav5595}]**
     bar[u][{spin5596}, {colf5905}, {flav6129}]**yu[{flav5906, flav5595}]**
     conj[yu][{flav5906, flav6129}])/(eps*Ms^4) - 
  ((I/8)*At^2*(-4 - 5*eps + 2*eps*L[Ms^2, \[Mu]^2])*
    cov[{lor1}, conj[H][{gauge6151}]]**gamma[{lor1}, {spin6024, spin6023}]**
     H[{gauge6151}]**bar[e][{spin6024}, {flav5585}]**
     e[{spin6023}, {flav6022}]**ye[{flav5744, flav6022}]**
     conj[ye][{flav5744, flav5585}])/(eps*Ms^4) - 
  ((I/8)*At^2*(-4 - 5*eps + 2*eps*L[Ms^2, \[Mu]^2])*
    cov[{lor1}, conj[H][{gauge6151}]]**gamma[{lor1}, {spin6046, spin6045}]**
     H[{gauge6151}]**bar[b][{spin6046}, {colf5773}, {flav5587}]**
     b[{spin6045}, {colf5773}, {flav6044}]**yd[{flav5774, flav6044}]**
     conj[yd][{flav5774, flav5587}])/(eps*Ms^4) + 
  ((I/4)*At^2*gamma[{lor1}, {spin6475, spin6476}]**H[{gauge7053}]**
     cov[{lor1}, l[{spin6476}, {gauge6191}, {flav6474}]]**
     bar[l][{spin6475}, {gauge7053}, {flav6978}]**ye[{flav6978, flav6722}]**
     conj[H][{gauge6191}]**conj[ye][{flav6474, flav6722}])/Ms^4 + 
  ((I/4)*At^2*gamma[{lor1}, {spin6478, spin6479}]**H[{gauge7053}]**
     cov[{lor1}, q[{spin6479}, {gauge6198}, {colf6766}, {flav6477}]]**
     bar[q][{spin6478}, {gauge7053}, {colf6766}, {flav7010}]**
     yd[{flav7010, flav6767}]**conj[H][{gauge6198}]**
     conj[yd][{flav6477, flav6767}])/Ms^4 + 
  ((I/4)*At^2*gamma[{lor1}, {spin6481, spin6482}]**H[{gauge6207}]**
     cov[{lor1}, u[{spin6482}, {colf6804}, {flav6480}]]**
     bar[u][{spin6481}, {colf6804}, {flav7031}]**yu[{flav6805, flav6480}]**
     conj[H][{gauge6207}]**conj[yu][{flav6805, flav7031}])/Ms^4 + 
  ((I/4)*At^2*gamma[{lor1}, {spin6494, spin6495}]**H[{gauge6248}]**
     cov[{lor1}, e[{spin6495}, {flav6493}]]**bar[e][{spin6494}, {flav7015}]**
     ye[{flav6775, flav6493}]**conj[H][{gauge6248}]**
     conj[ye][{flav6775, flav7015}])/Ms^4 + 
  ((I/4)*At^2*gamma[{lor1}, {spin6497, spin6498}]**H[{gauge6257}]**
     cov[{lor1}, b[{spin6498}, {colf6814}, {flav6496}]]**
     bar[b][{spin6497}, {colf6814}, {flav7035}]**yd[{flav6815, flav6496}]**
     conj[H][{gauge6257}]**conj[yd][{flav6815, flav7035}])/Ms^4 + 
  ((I/4)*At^2*gamma[{lor1}, {spin6855, spin6854}]**H[{gauge6215}]**
     cov[{lor1}, bar[l][{spin6855}, {gauge6215}, {flav6483}]]**
     l[{spin6854}, {gauge7055}, {flav6853}]**ye[{flav6483, flav6561}]**
     conj[H][{gauge7055}]**conj[ye][{flav6853, flav6561}])/Ms^4 + 
  ((I/4)*At^2*gamma[{lor1}, {spin6901, spin6900}]**H[{gauge6222}]**
     cov[{lor1}, bar[q][{spin6901}, {gauge6222}, {colf6609}, {flav6485}]]**
     q[{spin6900}, {gauge7055}, {colf6609}, {flav6899}]**
     yd[{flav6485, flav6610}]**conj[H][{gauge7055}]**
     conj[yd][{flav6899, flav6610}])/Ms^4 + 
  ((I/4)*At^2*gamma[{lor1}, {spin6926, spin6925}]**H[{gauge6174}]**
     cov[{lor1}, bar[e][{spin6926}, {flav6470}]]**e[{spin6925}, {flav6924}]**
     ye[{flav6637, flav6924}]**conj[H][{gauge6174}]**
     conj[ye][{flav6637, flav6470}])/Ms^4 + 
  ((I/4)*At^2*gamma[{lor1}, {spin6948, spin6947}]**H[{gauge6183}]**
     cov[{lor1}, bar[b][{spin6948}, {colf6664}, {flav6472}]]**
     b[{spin6947}, {colf6664}, {flav6946}]**yd[{flav6665, flav6946}]**
     conj[H][{gauge6183}]**conj[yd][{flav6665, flav6472}])/Ms^4 + 
  ((I/4)*At^2*gamma[{lor1}, {spin6954, spin6953}]**H[{gauge6231}]**
     cov[{lor1}, bar[u][{spin6954}, {colf6674}, {flav6487}]]**
     u[{spin6953}, {colf6674}, {flav6952}]**yu[{flav6675, flav6952}]**
     conj[H][{gauge6231}]**conj[yu][{flav6675, flav6487}])/Ms^4 - 
  ((I/8)*At^2*(-4 - 3*eps + 2*eps*L[Ms^2, \[Mu]^2])*
    gamma[{lor1}, {spin7361, spin7362}]**H[{gauge7938}]**
     l[{spin7362}, {gauge7093}, {flav7360}]**
     cov[{lor1}, bar[l][{spin7361}, {gauge7938}, {flav7863}]]**
     ye[{flav7863, flav7607}]**conj[H][{gauge7093}]**
     conj[ye][{flav7360, flav7607}])/(eps*Ms^4) - 
  ((I/8)*At^2*(-4 - 3*eps + 2*eps*L[Ms^2, \[Mu]^2])*
    gamma[{lor1}, {spin7364, spin7365}]**H[{gauge7938}]**
     q[{spin7365}, {gauge7100}, {colf7649}, {flav7363}]**
     cov[{lor1}, bar[q][{spin7364}, {gauge7938}, {colf7649}, {flav7895}]]**
     yd[{flav7895, flav7650}]**conj[H][{gauge7100}]**
     conj[yd][{flav7363, flav7650}])/(eps*Ms^4) - 
  ((I/8)*At^2*(-4 - 3*eps + 2*eps*L[Ms^2, \[Mu]^2])*
    gamma[{lor1}, {spin7367, spin7368}]**H[{gauge7109}]**
     u[{spin7368}, {colf7685}, {flav7366}]**
     cov[{lor1}, bar[u][{spin7367}, {colf7685}, {flav7916}]]**
     yu[{flav7686, flav7366}]**conj[H][{gauge7109}]**
     conj[yu][{flav7686, flav7916}])/(eps*Ms^4) - 
  ((I/8)*At^2*(-4 - 3*eps + 2*eps*L[Ms^2, \[Mu]^2])*
    gamma[{lor1}, {spin7380, spin7381}]**H[{gauge7150}]**
     e[{spin7381}, {flav7379}]**cov[{lor1}, bar[e][{spin7380}, {flav7900}]]**
     ye[{flav7658, flav7379}]**conj[H][{gauge7150}]**
     conj[ye][{flav7658, flav7900}])/(eps*Ms^4) - 
  ((I/8)*At^2*(-4 - 3*eps + 2*eps*L[Ms^2, \[Mu]^2])*
    gamma[{lor1}, {spin7383, spin7384}]**H[{gauge7159}]**
     b[{spin7384}, {colf7695}, {flav7382}]**
     cov[{lor1}, bar[b][{spin7383}, {colf7695}, {flav7920}]]**
     yd[{flav7696, flav7382}]**conj[H][{gauge7159}]**
     conj[yd][{flav7696, flav7920}])/(eps*Ms^4) - 
  ((I/8)*At^2*(-4 - 3*eps + 2*eps*L[Ms^2, \[Mu]^2])*
    gamma[{lor1}, {spin7740, spin7739}]**H[{gauge7117}]**
     bar[l][{spin7740}, {gauge7117}, {flav7369}]**
     cov[{lor1}, l[{spin7739}, {gauge7940}, {flav7738}]]**
     ye[{flav7369, flav7447}]**conj[H][{gauge7940}]**
     conj[ye][{flav7738, flav7447}])/(eps*Ms^4) - 
  ((I/8)*At^2*(-4 - 3*eps + 2*eps*L[Ms^2, \[Mu]^2])*
    gamma[{lor1}, {spin7786, spin7785}]**H[{gauge7124}]**
     bar[q][{spin7786}, {gauge7124}, {colf7492}, {flav7371}]**
     cov[{lor1}, q[{spin7785}, {gauge7940}, {colf7492}, {flav7784}]]**
     yd[{flav7371, flav7493}]**conj[H][{gauge7940}]**
     conj[yd][{flav7784, flav7493}])/(eps*Ms^4) - 
  ((I/8)*At^2*(-4 - 3*eps + 2*eps*L[Ms^2, \[Mu]^2])*
    gamma[{lor1}, {spin7811, spin7810}]**H[{gauge7076}]**
     bar[e][{spin7811}, {flav7356}]**cov[{lor1}, e[{spin7810}, {flav7809}]]**
     ye[{flav7520, flav7809}]**conj[H][{gauge7076}]**
     conj[ye][{flav7520, flav7356}])/(eps*Ms^4) - 
  ((I/8)*At^2*(-4 - 3*eps + 2*eps*L[Ms^2, \[Mu]^2])*
    gamma[{lor1}, {spin7833, spin7832}]**H[{gauge7085}]**
     bar[b][{spin7833}, {colf7549}, {flav7358}]**
     cov[{lor1}, b[{spin7832}, {colf7549}, {flav7831}]]**
     yd[{flav7550, flav7831}]**conj[H][{gauge7085}]**
     conj[yd][{flav7550, flav7358}])/(eps*Ms^4) - 
  ((I/8)*At^2*(-4 - 3*eps + 2*eps*L[Ms^2, \[Mu]^2])*
    gamma[{lor1}, {spin7839, spin7838}]**H[{gauge7133}]**
     bar[u][{spin7839}, {colf7559}, {flav7373}]**
     cov[{lor1}, u[{spin7838}, {colf7559}, {flav7837}]]**
     yu[{flav7560, flav7837}]**conj[H][{gauge7133}]**
     conj[yu][{flav7560, flav7373}])/(eps*Ms^4) - 
  ((I/8)*At^2*(-4 - 5*eps + 2*eps*L[Ms^2, \[Mu]^2])*
    cov[{lor1}, H[{gauge5369}]]**gamma[{lor1}, {spin6046, spin6045}]**
     H[{gauge6151}]**bar[u][{spin6046}, {colf5773}, {flav5602}]**
     b[{spin6045}, {colf5773}, {flav6044}]**su2eps[{gauge6151, gauge5369}]**
     yd[{flav5774, flav6044}]**conj[yu][{flav5774, flav5602}])/(eps*Ms^4) - 
  ((I/8)*At^2*(-4 - 5*eps + 2*eps*L[Ms^2, \[Mu]^2])*
    cov[{lor1}, H[{gauge5395}]]**gamma[{lor1}, {spin5612, spin5613}]**
     H[{gauge6151}]**b[{spin5613}, {colf5905}, {flav5611}]**
     bar[u][{spin5612}, {colf5905}, {flav6129}]**
     su2eps[{gauge5395, gauge6151}]**yd[{flav5906, flav5611}]**
     conj[yu][{flav5906, flav6129}])/(eps*Ms^4) - 
  ((I/8)*At^2*(-4 - 5*eps + 2*eps*L[Ms^2, \[Mu]^2])*
    cov[{lor1}, conj[H][{gauge5321}]]**gamma[{lor1}, {spin6052, spin6051}]**
     bar[b][{spin6052}, {colf5783}, {flav5587}]**u[{spin6051}, {colf5783}, 
      {flav6050}]**su2eps[{gauge5321, gauge6153}]**yu[{flav5784, flav6050}]**
     conj[H][{gauge6153}]**conj[yd][{flav5784, flav5587}])/(eps*Ms^4) - 
  ((I/8)*At^2*(-4 - 5*eps + 2*eps*L[Ms^2, \[Mu]^2])*
    cov[{lor1}, conj[H][{gauge5345}]]**gamma[{lor1}, {spin5596, spin5597}]**
     u[{spin5597}, {colf5915}, {flav5595}]**bar[b][{spin5596}, {colf5915}, 
      {flav6133}]**su2eps[{gauge6153, gauge5345}]**yu[{flav5916, flav5595}]**
     conj[H][{gauge6153}]**conj[yd][{flav5916, flav6133}])/(eps*Ms^4) + 
  ((I/4)*At^2*gamma[{lor1}, {spin6481, spin6482}]**
     cov[{lor1}, u[{spin6482}, {colf6814}, {flav6480}]]**
     bar[b][{spin6481}, {colf6814}, {flav7035}]**
     su2eps[{gauge7055, gauge6207}]**yu[{flav6815, flav6480}]**
     conj[H][{gauge6207}]**conj[H][{gauge7055}]**
     conj[yd][{flav6815, flav7035}])/Ms^4 + 
  ((I/4)*At^2*gamma[{lor1}, {spin6497, spin6498}]**H[{gauge6257}]**
     H[{gauge7053}]**cov[{lor1}, b[{spin6498}, {colf6804}, {flav6496}]]**
     bar[u][{spin6497}, {colf6804}, {flav7031}]**
     su2eps[{gauge6257, gauge7053}]**yd[{flav6805, flav6496}]**
     conj[yu][{flav6805, flav7031}])/Ms^4 + 
  ((I/4)*At^2*gamma[{lor1}, {spin6948, spin6947}]**H[{gauge6231}]**
     H[{gauge7053}]**cov[{lor1}, bar[u][{spin6948}, {colf6664}, {flav6487}]]**
     b[{spin6947}, {colf6664}, {flav6946}]**su2eps[{gauge7053, gauge6231}]**
     yd[{flav6665, flav6946}]**conj[yu][{flav6665, flav6487}])/Ms^4 + 
  ((I/4)*At^2*gamma[{lor1}, {spin6954, spin6953}]**
     cov[{lor1}, bar[b][{spin6954}, {colf6674}, {flav6472}]]**
     u[{spin6953}, {colf6674}, {flav6952}]**su2eps[{gauge6183, gauge7055}]**
     yu[{flav6675, flav6952}]**conj[H][{gauge6183}]**conj[H][{gauge7055}]**
     conj[yd][{flav6675, flav6472}])/Ms^4 - 
  ((I/8)*At^2*(-4 - 3*eps + 2*eps*L[Ms^2, \[Mu]^2])*
    gamma[{lor1}, {spin7367, spin7368}]**u[{spin7368}, {colf7695}, 
      {flav7366}]**cov[{lor1}, bar[b][{spin7367}, {colf7695}, {flav7920}]]**
     su2eps[{gauge7940, gauge7109}]**yu[{flav7696, flav7366}]**
     conj[H][{gauge7109}]**conj[H][{gauge7940}]**
     conj[yd][{flav7696, flav7920}])/(eps*Ms^4) - 
  ((I/8)*At^2*(-4 - 3*eps + 2*eps*L[Ms^2, \[Mu]^2])*
    gamma[{lor1}, {spin7383, spin7384}]**H[{gauge7159}]**H[{gauge7938}]**
     b[{spin7384}, {colf7685}, {flav7382}]**
     cov[{lor1}, bar[u][{spin7383}, {colf7685}, {flav7916}]]**
     su2eps[{gauge7159, gauge7938}]**yd[{flav7686, flav7382}]**
     conj[yu][{flav7686, flav7916}])/(eps*Ms^4) - 
  ((I/8)*At^2*(-4 - 3*eps + 2*eps*L[Ms^2, \[Mu]^2])*
    gamma[{lor1}, {spin7833, spin7832}]**H[{gauge7133}]**H[{gauge7938}]**
     bar[u][{spin7833}, {colf7549}, {flav7373}]**
     cov[{lor1}, b[{spin7832}, {colf7549}, {flav7831}]]**
     su2eps[{gauge7938, gauge7133}]**yd[{flav7550, flav7831}]**
     conj[yu][{flav7550, flav7373}])/(eps*Ms^4) - 
  ((I/8)*At^2*(-4 - 3*eps + 2*eps*L[Ms^2, \[Mu]^2])*
    gamma[{lor1}, {spin7839, spin7838}]**bar[b][{spin7839}, {colf7559}, 
      {flav7358}]**cov[{lor1}, u[{spin7838}, {colf7559}, {flav7837}]]**
     su2eps[{gauge7085, gauge7940}]**yu[{flav7560, flav7837}]**
     conj[H][{gauge7085}]**conj[H][{gauge7940}]**
     conj[yd][{flav7560, flav7358}])/(eps*Ms^4) - 
  (At^2*d*(-4 - 3*eps + 2*eps*L[Ms^2, \[Mu]^2])*
    H[{gauge2355}]**bar[e][{spin2766}, {flav2765}]**
     l[{spin2766}, {gauge3850}, {flav3648}]**ye[{flav2917, flav3140}]**
     conj[H][{gauge2355}]**conj[H][{gauge3850}]**
     conj[ye][{flav2917, flav2765}]**conj[ye][{flav3648, flav3140}])/
   (16*eps*Ms^4) - (At^2*d*(-4 - 3*eps + 2*eps*L[Ms^2, \[Mu]^2])*
    H[{gauge2364}]**bar[b][{spin2768}, {colf2955}, {flav2767}]**
     q[{spin2768}, {gauge3850}, {colf2955}, {flav3694}]**
     yd[{flav2957, flav3200}]**conj[H][{gauge2364}]**conj[H][{gauge3850}]**
     conj[yd][{flav2957, flav2767}]**conj[yd][{flav3694, flav3200}])/
   (16*eps*Ms^4) - (At^2*d*(-4 - 3*eps + 2*eps*L[Ms^2, \[Mu]^2])*
    H[{gauge2396}]**H[{gauge3848}]**bar[l][{spin2779}, {gauge2396}, 
      {flav2778}]**e[{spin2779}, {flav3719}]**ye[{flav2778, flav2867}]**
     ye[{flav3240, flav3719}]**conj[H][{gauge3848}]**
     conj[ye][{flav3240, flav2867}])/(16*eps*Ms^4) - 
  (At^2*d*(-4 - 3*eps + 2*eps*L[Ms^2, \[Mu]^2])*
    H[{gauge2403}]**H[{gauge3848}]**bar[q][{spin2781}, {gauge2403}, 
      {colf2905}, {flav2780}]**b[{spin2781}, {colf2905}, {flav3741}]**
     yd[{flav2780, flav2907}]**yd[{flav3292, flav3741}]**
     conj[H][{gauge3848}]**conj[yd][{flav3292, flav2907}])/(16*eps*Ms^4) + 
  (At^2*d*(-4 - 3*eps + 2*eps*L[Ms^2, \[Mu]^2])*
    H[{gauge2429}]**H[{gauge3848}]**e[{spin3774}, {flav2788}]**
     bar[l][{spin3774}, {gauge3848}, {flav3773}]**ye[{flav3041, flav2788}]**
     ye[{flav3773, flav3361}]**conj[H][{gauge2429}]**
     conj[ye][{flav3041, flav3361}])/(16*eps*Ms^4) + 
  (At^2*d*(-4 - 3*eps + 2*eps*L[Ms^2, \[Mu]^2])*
    H[{gauge2438}]**H[{gauge3848}]**b[{spin3806}, {colf3079}, {flav2791}]**
     bar[q][{spin3806}, {gauge3848}, {colf3079}, {flav3805}]**
     yd[{flav3081, flav2791}]**yd[{flav3805, flav3451}]**
     conj[H][{gauge2438}]**conj[yd][{flav3081, flav3451}])/(16*eps*Ms^4) + 
  (At^2*d*(-4 - 3*eps + 2*eps*L[Ms^2, \[Mu]^2])*
    H[{gauge3850}]**l[{spin3811}, {gauge2372}, {flav2769}]**
     bar[e][{spin3811}, {flav3810}]**ye[{flav3459, flav2991}]**
     conj[H][{gauge2372}]**conj[H][{gauge3850}]**
     conj[ye][{flav2769, flav2991}]**conj[ye][{flav3459, flav3810}])/
   (16*eps*Ms^4) + (At^2*d*(-4 - 3*eps + 2*eps*L[Ms^2, \[Mu]^2])*
    H[{gauge3850}]**q[{spin3831}, {gauge2379}, {colf3029}, {flav2772}]**
     bar[b][{spin3831}, {colf3029}, {flav3830}]**yd[{flav3562, flav3031}]**
     conj[H][{gauge2379}]**conj[H][{gauge3850}]**
     conj[yd][{flav2772, flav3031}]**conj[yd][{flav3562, flav3830}])/
   (16*eps*Ms^4) - ((I/8)*At^2*(-4 - 5*eps + 2*eps*L[Ms^2, \[Mu]^2])*
    cov[{lor1}, H[{gauge5378}]]**gamma[{lor1}, {spin5606, spin5607}]**
     q[{spin5607}, {gauge5605}, {colf5839}, {flav5604}]**
     bar[q][{spin5606}, {gauge6091}, {colf5839}, {flav6089}]**
     su2eps[{gauge5605, gauge5378}]**su2eps[{gauge6091, gauge6153}]**
     yu[{flav6089, flav5840}]**conj[H][{gauge6153}]**
     conj[yu][{flav5604, flav5840}])/(eps*Ms^4) - 
  ((I/8)*At^2*(-4 - 5*eps + 2*eps*L[Ms^2, \[Mu]^2])*
    cov[{lor1}, conj[H][{gauge5304}]]**gamma[{lor1}, {spin5973, spin5972}]**
     H[{gauge6151}]**bar[q][{spin5973}, {gauge5584}, {colf5689}, {flav5582}]**
     q[{spin5972}, {gauge5971}, {colf5689}, {flav5970}]**
     su2eps[{gauge5584, gauge5304}]**su2eps[{gauge5971, gauge6151}]**
     yu[{flav5582, flav5690}]**conj[yu][{flav5970, flav5690}])/(eps*Ms^4) + 
  ((I/4)*At^2*gamma[{lor1}, {spin6491, spin6492}]**H[{gauge6240}]**
     cov[{lor1}, q[{spin6492}, {gauge6490}, {colf6736}, {flav6489}]]**
     bar[q][{spin6491}, {gauge6993}, {colf6736}, {flav6991}]**
     su2eps[{gauge6490, gauge6240}]**su2eps[{gauge6993, gauge7055}]**
     yu[{flav6991, flav6737}]**conj[H][{gauge7055}]**
     conj[yu][{flav6489, flav6737}])/Ms^4 + 
  ((I/4)*At^2*gamma[{lor1}, {spin6875, spin6874}]**H[{gauge7053}]**
     cov[{lor1}, bar[q][{spin6875}, {gauge6469}, {colf6579}, {flav6467}]]**
     q[{spin6874}, {gauge6873}, {colf6579}, {flav6872}]**
     su2eps[{gauge6469, gauge6166}]**su2eps[{gauge6873, gauge7053}]**
     yu[{flav6467, flav6580}]**conj[H][{gauge6166}]**
     conj[yu][{flav6872, flav6580}])/Ms^4 - 
  ((I/8)*At^2*(-4 - 3*eps + 2*eps*L[Ms^2, \[Mu]^2])*
    gamma[{lor1}, {spin7377, spin7378}]**H[{gauge7142}]**
     q[{spin7378}, {gauge7376}, {colf7620}, {flav7375}]**
     cov[{lor1}, bar[q][{spin7377}, {gauge7878}, {colf7620}, {flav7876}]]**
     su2eps[{gauge7376, gauge7142}]**su2eps[{gauge7878, gauge7940}]**
     yu[{flav7876, flav7621}]**conj[H][{gauge7940}]**
     conj[yu][{flav7375, flav7621}])/(eps*Ms^4) - 
  ((I/8)*At^2*(-4 - 3*eps + 2*eps*L[Ms^2, \[Mu]^2])*
    gamma[{lor1}, {spin7760, spin7759}]**H[{gauge7938}]**
     bar[q][{spin7760}, {gauge7355}, {colf7464}, {flav7353}]**
     cov[{lor1}, q[{spin7759}, {gauge7758}, {colf7464}, {flav7757}]]**
     su2eps[{gauge7355, gauge7068}]**su2eps[{gauge7758, gauge7938}]**
     yu[{flav7353, flav7465}]**conj[H][{gauge7068}]**
     conj[yu][{flav7757, flav7465}])/(eps*Ms^4) + 
  (At^2*d*(-4 - 3*eps + 2*eps*L[Ms^2, \[Mu]^2])*
    H[{gauge2388}]**u[{spin3787}, {colf3065}, {flav2775}]**
     bar[q][{spin3787}, {gauge3788}, {colf3065}, {flav3786}]**
     su2eps[{gauge3788, gauge3850}]**yu[{flav3067, flav2775}]**
     yu[{flav3786, flav3389}]**conj[H][{gauge2388}]**conj[H][{gauge3850}]**
     conj[yu][{flav3067, flav3389}])/(16*eps*Ms^4) - 
  (At^2*d*(-4 - 3*eps + 2*eps*L[Ms^2, \[Mu]^2])*
    H[{gauge2403}]**bar[q][{spin2781}, {gauge2403}, {colf2905}, {flav2780}]**
     u[{spin2781}, {colf2905}, {flav3747}]**su2eps[{gauge3299, gauge3850}]**
     yd[{flav2780, flav2907}]**yu[{flav3302, flav3747}]**
     conj[H][{gauge3299}]**conj[H][{gauge3850}]**
     conj[yd][{flav3302, flav2907}])/(16*eps*Ms^4) - 
  (At^2*d*(-4 - 3*eps + 2*eps*L[Ms^2, \[Mu]^2])*
    H[{gauge2412}]**H[{gauge2954}]**bar[u][{spin2783}, {colf2955}, 
      {flav2782}]**q[{spin2783}, {gauge3850}, {colf2955}, {flav3694}]**
     su2eps[{gauge2954, gauge2412}]**yd[{flav2957, flav3200}]**
     conj[H][{gauge3850}]**conj[yd][{flav3694, flav3200}]**
     conj[yu][{flav2957, flav2782}])/(16*eps*Ms^4) - 
  (At^2*d*(-4 - 3*eps + 2*eps*L[Ms^2, \[Mu]^2])*
    H[{gauge2412}]**H[{gauge3848}]**bar[u][{spin2783}, {colf2941}, 
      {flav2782}]**q[{spin2783}, {gauge3668}, {colf2941}, {flav3667}]**
     su2eps[{gauge3668, gauge3848}]**yu[{flav2943, flav3162}]**
     conj[H][{gauge2412}]**conj[yu][{flav2943, flav2782}]**
     conj[yu][{flav3667, flav3162}])/(16*eps*Ms^4) + 
  (At^2*d*(-4 - 3*eps + 2*eps*L[Ms^2, \[Mu]^2])*
    H[{gauge2421}]**H[{gauge3116}]**q[{spin3827}, {gauge2785}, {colf3015}, 
      {flav2784}]**bar[u][{spin3827}, {colf3015}, {flav3826}]**
     su2eps[{gauge2785, gauge2421}]**yu[{flav3552, flav3017}]**
     conj[H][{gauge3116}]**conj[yu][{flav2784, flav3017}]**
     conj[yu][{flav3552, flav3826}])/(16*eps*Ms^4) - 
  (At^2*d*(-4 - 3*eps + 2*eps*L[Ms^2, \[Mu]^2])*
    H[{gauge3101}]**bar[q][{spin2763}, {gauge2764}, {colf2891}, {flav2762}]**
     u[{spin2763}, {colf2891}, {flav3747}]**su2eps[{gauge2764, gauge2347}]**
     yu[{flav2762, flav2893}]**yu[{flav3302, flav3747}]**
     conj[H][{gauge2347}]**conj[H][{gauge3101}]**
     conj[yu][{flav3302, flav2893}])/(16*eps*Ms^4) + 
  (At^2*d*(-4 - 3*eps + 2*eps*L[Ms^2, \[Mu]^2])*
    H[{gauge3549}]**H[{gauge3848}]**q[{spin3827}, {gauge2379}, {colf3029}, 
      {flav2772}]**bar[u][{spin3827}, {colf3029}, {flav3826}]**
     su2eps[{gauge3549, gauge3848}]**yd[{flav3552, flav3031}]**
     conj[H][{gauge2379}]**conj[yd][{flav2772, flav3031}]**
     conj[yu][{flav3552, flav3826}])/(16*eps*Ms^4) + 
  (At^2*d*(-4 - 3*eps + 2*eps*L[Ms^2, \[Mu]^2])*
    H[{gauge3848}]**u[{spin3806}, {colf3079}, {flav2775}]**
     bar[q][{spin3806}, {gauge3848}, {colf3079}, {flav3805}]**
     su2eps[{gauge3078, gauge2388}]**yd[{flav3805, flav3451}]**
     yu[{flav3081, flav2775}]**conj[H][{gauge2388}]**conj[H][{gauge3078}]**
     conj[yd][{flav3081, flav3451}])/(16*eps*Ms^4) + 
  (At^2*d*(-4 - 3*eps + 2*eps*L[Ms^2, \[Mu]^2])*
    H[{gauge2421}]**q[{spin3831}, {gauge2785}, {colf3015}, {flav2784}]**
     bar[b][{spin3831}, {colf3015}, {flav3830}]**
     su2eps[{gauge2785, gauge2421}]**su2eps[{gauge3850, gauge3116}]**
     yu[{flav3562, flav3017}]**conj[H][{gauge3116}]**conj[H][{gauge3850}]**
     conj[yd][{flav3562, flav3830}]**conj[yu][{flav2784, flav3017}])/
   (16*eps*Ms^4) + (At^2*d*(-4 - 3*eps + 2*eps*L[Ms^2, \[Mu]^2])*
    H[{gauge2438}]**H[{gauge3129}]**b[{spin3787}, {colf3065}, {flav2791}]**
     bar[q][{spin3787}, {gauge3788}, {colf3065}, {flav3786}]**
     su2eps[{gauge2438, gauge3129}]**su2eps[{gauge3788, gauge3850}]**
     yd[{flav3067, flav2791}]**yu[{flav3786, flav3389}]**
     conj[H][{gauge3850}]**conj[yu][{flav3067, flav3389}])/(16*eps*Ms^4) - 
  (At^2*d*(-4 - 3*eps + 2*eps*L[Ms^2, \[Mu]^2])*
    H[{gauge3101}]**H[{gauge3848}]**bar[q][{spin2763}, {gauge2764}, 
      {colf2891}, {flav2762}]**b[{spin2763}, {colf2891}, {flav3741}]**
     su2eps[{gauge2764, gauge2347}]**su2eps[{gauge3848, gauge3101}]**
     yd[{flav3292, flav3741}]**yu[{flav2762, flav2893}]**
     conj[H][{gauge2347}]**conj[yu][{flav3292, flav2893}])/(16*eps*Ms^4) - 
  (At^2*d*(-4 - 3*eps + 2*eps*L[Ms^2, \[Mu]^2])*
    H[{gauge3848}]**bar[b][{spin2768}, {colf2941}, {flav2767}]**
     q[{spin2768}, {gauge3668}, {colf2941}, {flav3667}]**
     su2eps[{gauge2364, gauge3108}]**su2eps[{gauge3668, gauge3848}]**
     yu[{flav2943, flav3162}]**conj[H][{gauge2364}]**conj[H][{gauge3108}]**
     conj[yd][{flav2943, flav2767}]**conj[yu][{flav3667, flav3162}])/
   (16*eps*Ms^4)}
